#!/bin/bash
IP=193.150.86.112
PORT=22903

set -ex

case $1 in
  grab)
    scp -r -P $PORT root@${IP}:$2 $3
    ;;
  scp)
    scp -r -P $PORT $2 root@${IP}:$3
    ;;
  upload)
    rsync -arvz --exclude=train/checkpoint.pt --progress -e "ssh -p $PORT" ./train root@${IP}:./
    ssh -p $PORT root@${IP} apt-get -y install vim htop
    ssh -p $PORT root@${IP} bash -c 'yes | /opt/conda/bin/conda install h5py'
    ssh -p $PORT root@${IP} "cat > /root/.vimrc" <<'EOF'
syntax on
set et
set shiftwidth=4
set tabstop=4
EOF
    ssh -p $PORT root@${IP} "cat > /root/.tmux.conf" <<'EOF'
setw -g mouse on
EOF
    ;;
  ssh)
    shift 1
    TERM=xterm-256color ssh -p $PORT root@${IP} "$@"
    ;;
  checkpoint)
     while true
     do
      scp -r -P $PORT root@${IP}:./train/checkpoint.pt ./train/checkpoint.pt
      python3 -c "import torch ; print(torch.load('./train/checkpoint.pt')['training_losses'])"
      sleep 200
    done
    ;;
esac
