#!/bin/bash
IP=75.142.233.14
PORT=27430

case $1 in
  scp)
    scp -r -P $PORT $2 root@${IP}:$3
    ;;
  seed)
    scp -r -P $PORT ./train root@${IP}:./train
    ssh -p $PORT root@${IP} apt-get -y install vim htop
    ssh -p $PORT root@${IP} "cat > /root/.vimrc" <<'EOF'
syntax on
set et
set shiftwidth=4
set tabstop=4
EOF
    ;;
  ssh)
    TERM=xterm-256color ssh -p $PORT root@${IP}
    ;;
  grab)
     while true
     do
      scp -r -P $PORT root@${IP}:./train/checkpoint.pt ./train/checkpoint.pt
      sleep 200
    done
    ;;
esac
